ERROR - 2022-06-04 05:19:32 --> Error connecting to the database: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
CRITICAL - 2022-06-04 05:19:32 --> Unable to connect to the database.
Main connection [postgre]: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
#0 D:\xampp\htdocs\202210079\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\202210079\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "u"."id"...', Array, false)
#2 D:\xampp\htdocs\202210079\app\Controllers\User.php(43): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\202210079\system\CodeIgniter.php(832): App\Controllers\User->get_user('2')
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 D:\xampp\htdocs\202210079\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-06-04 05:33:37 --> Error connecting to the database: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
CRITICAL - 2022-06-04 05:33:37 --> Unable to connect to the database.
Main connection [postgre]: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
#0 D:\xampp\htdocs\202210079\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\202210079\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "u"."id"...', Array, false)
#2 D:\xampp\htdocs\202210079\app\Controllers\User.php(17): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\202210079\system\CodeIgniter.php(832): App\Controllers\User->index()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 D:\xampp\htdocs\202210079\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-06-04 05:34:44 --> Error connecting to the database: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
CRITICAL - 2022-06-04 05:34:44 --> Unable to connect to the database.
Main connection [postgre]: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
#0 D:\xampp\htdocs\202210079\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\202210079\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "u"."id"...', Array, false)
#2 D:\xampp\htdocs\202210079\app\Controllers\User.php(17): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\202210079\system\CodeIgniter.php(832): App\Controllers\User->index()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 D:\xampp\htdocs\202210079\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-06-04 05:37:10 --> Error connecting to the database: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
CRITICAL - 2022-06-04 05:37:10 --> Unable to connect to the database.
Main connection [postgre]: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
#0 D:\xampp\htdocs\202210079\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\202210079\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "u"."id"...', Array, false)
#2 D:\xampp\htdocs\202210079\app\Controllers\User.php(17): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\202210079\system\CodeIgniter.php(832): App\Controllers\User->index()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 D:\xampp\htdocs\202210079\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-06-04 09:15:54 --> Error connecting to the database: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
CRITICAL - 2022-06-04 09:15:54 --> Unable to connect to the database.
Main connection [postgre]: Call to undefined function CodeIgniter\Database\Postgre\pg_connect()
#0 D:\xampp\htdocs\202210079\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\202210079\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT "u"."id"...', Array, false)
#2 D:\xampp\htdocs\202210079\app\Controllers\User.php(17): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\202210079\system\CodeIgniter.php(832): App\Controllers\User->index()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 D:\xampp\htdocs\202210079\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-06-04 09:23:38 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2022-06-04 09:23:38 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

#0 D:\xampp\htdocs\202210079\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\202210079\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT `u`.`id`...', Array, false)
#2 D:\xampp\htdocs\202210079\app\Controllers\User.php(17): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\202210079\system\CodeIgniter.php(832): App\Controllers\User->index()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 D:\xampp\htdocs\202210079\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-06-04 09:31:27 --> Table 'restfulapi.user' doesn't exist
CRITICAL - 2022-06-04 09:31:27 --> Table 'restfulapi.user' doesn't exist
#0 D:\xampp\htdocs\202210079\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT `u`.`id`...', 0)
#1 D:\xampp\htdocs\202210079\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT `u`.`id`...')
#2 D:\xampp\htdocs\202210079\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT `u`.`id`...')
#3 D:\xampp\htdocs\202210079\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT `u`.`id`...', Array, false)
#4 D:\xampp\htdocs\202210079\app\Controllers\User.php(18): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\202210079\system\CodeIgniter.php(832): App\Controllers\User->get_user_list()
#6 D:\xampp\htdocs\202210079\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 D:\xampp\htdocs\202210079\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-06-04 10:35:44 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 10:35:50 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-06-04 11:01:54 --> Error connecting to the database: Access denied for user ''@'localhost' (using password: NO)
CRITICAL - 2022-06-04 11:01:54 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
#0 D:\xampp\htdocs\202210079\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\202210079\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT `u`.`id`...', Array, false)
#2 D:\xampp\htdocs\202210079\app\Controllers\User.php(18): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\202210079\system\CodeIgniter.php(832): App\Controllers\User->get_user_list()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#5 D:\xampp\htdocs\202210079\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-06-04 11:01:54 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:01:58 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:33:37 --> Cannot declare class App\Controllers\User because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:37:06 --> Call to undefined method CodeIgniter\Router\RouteCollection::resources()
#0 D:\xampp\htdocs\202210079\system\Router\RouteCollection.php(607): CodeIgniter\CodeIgniter->Config\{closure}(Object(CodeIgniter\Router\RouteCollection))
#1 D:\xampp\htdocs\202210079\app\Config\Routes.php(52): CodeIgniter\Router\RouteCollection->group('ApiAuth', Array, Object(Closure))
#2 D:\xampp\htdocs\202210079\system\CodeIgniter.php(713): require('D:\\xampp\\htdocs...')
#3 D:\xampp\htdocs\202210079\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-04 11:37:06 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:38:02 --> Cannot declare class App\Controllers\User because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:38:20 --> Cannot declare class App\Controllers\User because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:38:34 --> Cannot declare class App\Controllers\User because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:38:39 --> Cannot declare class App\Controllers\User because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:42:24 --> Cannot declare class App\Controllers\User because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:43:56 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:50:52 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 11:56:05 --> Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 439, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 D:\xampp\htdocs\202210079\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 D:\xampp\htdocs\202210079\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-04 11:56:05 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 12:06:53 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 12:07:10 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 12:07:13 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 12:11:08 --> Cannot declare class App\Controllers\User because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 12:11:19 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 12:11:48 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 12:14:00 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 12:15:03 --> Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 439, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 D:\xampp\htdocs\202210079\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 D:\xampp\htdocs\202210079\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-04 12:15:03 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 12:15:08 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 12:15:42 --> Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 439, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 D:\xampp\htdocs\202210079\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 D:\xampp\htdocs\202210079\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-04 12:15:42 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-04 13:10:32 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
