CRITICAL - 2022-06-10 22:51:05 --> Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 439, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 D:\xampp\htdocs\202210079\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 D:\xampp\htdocs\202210079\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-10 22:51:05 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:00:33 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:03:17 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:11:33 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:11:54 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:11:58 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:11:59 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:12:22 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:12:23 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:24:12 --> Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 439, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 D:\xampp\htdocs\202210079\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 D:\xampp\htdocs\202210079\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-10 23:24:12 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:25:27 --> Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 439, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 D:\xampp\htdocs\202210079\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 D:\xampp\htdocs\202210079\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-10 23:25:27 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:25:53 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:32:17 --> Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 439, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 D:\xampp\htdocs\202210079\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 D:\xampp\htdocs\202210079\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-10 23:32:17 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:32:23 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:32:33 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:32:40 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:46:40 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:52:04 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:52:05 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 404 No...', true, 404)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\PageNotFoundException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-06-10 23:58:45 --> Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32)
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 439, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Toolbar.php(439): header('Content-Type: a...')
#2 D:\xampp\htdocs\202210079\app\Config\Events.php(48): CodeIgniter\Debug\Toolbar->respond()
#3 D:\xampp\htdocs\202210079\system\Events\Events.php(149): CodeIgniter\Events\Events::Config\{closure}()
#4 D:\xampp\htdocs\202210079\system\CodeIgniter.php(308): CodeIgniter\Events\Events::trigger('pre_system')
#5 D:\xampp\htdocs\202210079\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2022-06-10 23:58:45 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at D:\xampp\htdocs\202210079\app\Config\Events.php:32) in D:\xampp\htdocs\202210079\system\Debug\Exceptions.php:112
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'D:\\xampp\\htdocs...', 112, Array)
#1 D:\xampp\htdocs\202210079\system\Debug\Exceptions.php(112): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
